### Numpy 

Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical function to operate on these data structres. In this lesson, we will cover the basics of NumPy, focusing on arrays and Vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np
 
#Create arrays using numpy
arr1=np.array([1,2,3,4,5,6])

In [3]:
print(arr1)

[1 2 3 4 5 6]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
arr1.shape

(6,)

In [7]:
arr2=np.array([1,2,3,4,5])

In [8]:
arr2.reshape(1,5) #1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [11]:
arr3=np.array([[1,2,3,4,5,6,7]])
arr3.shape

(1, 7)

In [14]:
## 2D array
arr4=np.array([[1,2,3,4],[2,3,4,5]])
print(arr4)
print(arr4.shape)

[[1 2 3 4]
 [2 3 4 5]]
(2, 4)


In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#idetity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
## Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape", arr.shape)
print("Number of Dimensions:", arr.ndim)
print("Size (Number of elements):",arr.size)
print("Data type:",arr.dtype)
print("Item Size (In Bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of Dimensions: 2
Size (Number of elements): 6
Data type: int32
Item Size (In Bytes): 4


In [24]:
## Numpy vectorized operations
arrr1=np.array([1,2,3,4,5])
arrr2=np.array([10,20,30,40,50])

## Element wise addition
print("Addition:",arrr1+arrr2)

## Element wise substraction
print("Substraction:",arrr1-arrr2)

## Element wise Multiplication
print("Multiplicatiom:",arrr1*arrr2)

## Element wise division
print("Division:",arrr1/arrr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplicatiom: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [26]:
## Universal functions( Means some function the applies to all the elements in an array )
arr=np.array([2,3,4,5,6])
# Square root
print(np.sqrt(arr))
## Exponential 
print(np.exp(arr))
## Sine
print(np.sin(arr))
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [28]:
## Array slicing and indexing
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array: \n",arr)

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
arr[2][1]

8

In [34]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [35]:
arr[0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr[2:]

array([[7, 8, 9]])

In [37]:
arr[2][1:]

array([8, 9])

In [40]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
arr[1:,2:]

array([[6],
       [9]])

In [44]:
### Modify Array elements
arr[0,0]=100

In [45]:
arr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [46]:
arr[1:]=100
arr

array([[100,   2,   3],
       [100, 100, 100],
       [100, 100, 100]])

In [47]:
### Statistical concept normalization
## to have a mean of 0 and standard deviation 1

data = np.array([1,2,3,4,5])
# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized Data:", normalized_data)

#Normalization is converting data in a way that your mean is 0 and your standard deviation 1

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [48]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean:", mean)

# median
median = np.median(data)
print("Median:", median)

#standard deviation
standard_deviation = np.std(data)
print("Standard Deviation:",standard_deviation)

# variance
variance = np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [50]:
#Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])

In [51]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])